# Generated by Django 3.1.7 on 2021-09-25 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210925_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='title',
            new_name='name',
        ),
    ]
